# -*- coding: utf-8 -*-
"""PYTHONPROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aHwKvUIPcF7hWxAYscsQthUN57A8hxxT

# **Exploring Crime Trends - Crime Against Women Analysis Project**




The "Crime against Women Analysis Project" is a research project aimed at exploring crime trends related to violence and harassment against women. The project seeks to analyze and interpret data related to various types of crimes committed against women, including sexual assault, domestic violence, stalking, and other forms of gender-based violence. The project will also examine the factors that contribute to the prevalence of these crimes and the effectiveness of current policies and interventions in preventing and addressing them. Through this analysis, the project aims to provide insights and recommendations for policymakers, law enforcement agencies, and other stakeholders to develop strategies to prevent and reduce crime against women.

# **Crime Against Women**
One of the most concerning aspects of crime in India is the high incidence of violence against women. According to data from the National Crime Records Bureau, there were over 400,000 cases of crimes against women reported in 2019. These crimes include rape, sexual harassment, domestic violence, and dowry-related violence. Despite efforts by the government and NGOs to address this issue, it remains a major problem in India.
"""

!pip install pandas --upgrade --quiet
!pip install matplotlib

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
!pip install matplotlib
!pip install plotly
import plotly.express as px

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os

"""downloading all libraries"""

from google.colab import files

uploaded = files.upload()

"""The above excel sheet has data from the past 10 years i.e 2011 to 2021 about crimes against women of all states in India - rape, kidnapping and abduction, dowry deaths, domestic violence, human trafficking, assault on modesty,sexual harrassment and imortal trafficking"""

import pandas as pd
df = pd.read_excel('crime_women.xlsx')
print(df)

df.STATES=df.STATES.astype("string")
df.dtypes.to_frame()

print(df.STATES.unique())

df.head()

#stroring the sum of all crimes comitted within a state statewise
state_all_crimes = df.groupby('STATES').sum()

#droping the sum of year column
state_all_crimes.drop('YEAR',axis=1,inplace=True)

state_all_crimes.sort_values('TOTAL CRIMES AGAINST WOMEN',ascending=False)
state_all_crimes

state_all_crimes.info()

#all crimes count throughout the years
total_df=state_all_crimes.sum(axis=0).reset_index()
tf=pd.DataFrame(total_df)
tf

#plotting
#states v/s total crimes
import plotly.express as px
sorted_df = state_all_crimes.sort_values('TOTAL CRIMES AGAINST WOMEN',ascending=False)
fig = px.bar( x=tf["index"],y=tf[0], color=tf[0],
             labels={'x': "Crimes", 'y': "Count"}, title="Total Cases",
             color_continuous_scale='burg')
fig.show()

"""From the above graph it can be seen that **domestic violence** is the most prevalent crime across all states of India"""

#sates v/s total crimes
sorted_df = df.sort_values('TOTAL CRIMES AGAINST WOMEN',ascending=False)
fig = px.bar( x=sorted_df['STATES'],y=sorted_df["TOTAL CRIMES AGAINST WOMEN"], color=sorted_df["TOTAL CRIMES AGAINST WOMEN"],
             labels={'x': "States", 'y': "Count"}, title="TOTAL CRIMES AGAINST WOMEN",
             color_continuous_scale='burg')
fig.show()

"""The above graph is a statewise representation of the total crimes committed against women in India and the top states from above data are:


1.   Uttar Pradesh
2.   Madhya Pradesh
3.   West Bengal
4.   Rajasthan
5.   Maharashtra


"""

#states v/s  kidnapping and abduction

fig = px.bar( x=df['STATES'],y=df["KIDNAP & ABDUCTION"], color=df["KIDNAP & ABDUCTION"],
             labels={'x': "States", 'y': "Count"}, title="Kidnapping and Abduction Cases",
             color_continuous_scale='viridis')
fig.show()

"""The above bar graph demonstrates the states vs count of kidnapping and abduction of respective states
The countries with the most kidnapping and abduction are:


1.   Uttar Pradesh
2.   Bihar
3.   Assam
4.   Madhya Pradesh
5.   Maharashtra


"""

#states v/s  dowry

fig = px.bar( x=df['STATES'],y=df["DOWRY DEATHS"], color=df["DOWRY DEATHS"],
             labels={'x': "States", 'y': "Count"}, title="Deaths due to Dowry",
             color_continuous_scale='magma')
fig.show()

"""The above bar graph demonstrates the states vs count of death due to dowry in respective states The countries with the most deaths due to dowry are:


1.   Uttar Pradesh
2.   Bihar
3.   Madhya Pradesh
4.   West Bengal
5.   Tripura


"""

#states v/s  sexual harrassment
fig = px.bar( x=df['STATES'],y=df["SEXUAL HARRASSMENT"], color=df["SEXUAL HARRASSMENT"],
             labels={'x': "States", 'y': "Count"}, title="Cases reported of sexual harrassment",
             color_continuous_scale='turbo')
fig.show()

"""The above bar graph demonstrates the states vs cases reported sexual harrassment of respective states The countries with the most kidnapping and abduction are:


1.   Andhra Pradesh
2.   Maharashtra
3.   Uttar Pradesh
4.   Madhya Pradesh
5.   Kerala




"""

#states v/s  immortal trafficking
fig = px.bar( x=df['STATES'],y=df["IMORTAL TRAFFICKING"], color=df["IMORTAL TRAFFICKING"],
             labels={'x': "States", 'y': "Count"}, title="Cases reported of sexual harrassment",
             color_continuous_scale='portland')
fig.show()

#states vs ASSAULT ON MODESTY
fig = px.bar( x=df['STATES'],y=df["ASSAULT ON MODESTY"], color=df["ASSAULT ON MODESTY"],
             labels={'x': "States", 'y': "Count"}, title="Cases reported of assault of modesty",
             color_continuous_scale='electric')
fig.show()

"""The above bar graph demonstrates the states vs cases of assault on modesty of women in respective states The countries with the most assault on modesty of women are:



1.   Madhya Pradesh
2.   Maharashtra
3.   Uttar Pradesh
4.   Odisha
5.   Karnataka



"""

#states vs human trafficking
fig = px.bar( x=df['STATES'],y=df["HUMAN TRAFFICKING"], color=df["HUMAN TRAFFICKING"],
             labels={'x': "States", 'y': "Count"}, title="Cases reported of human trafficking",
             color_continuous_scale='blackbody')
fig.show()

"""The above bar graph demonstrates the states vs cases reported due to human trafficking respective states.The countries with the most cases reported due to human trafficking are:



1.   Madhya Pradesh
2.   Maharashtra
3.   Assam
4.   Andhra Pradesh
5.   West Bengal

"""

m=df.groupby(['STATES'])[['TOTAL CRIMES AGAINST WOMEN']].max().sort_values(['TOTAL CRIMES AGAINST WOMEN'],ascending=False)['TOTAL CRIMES AGAINST WOMEN']
colors = sns.color_palette('pastel')[0:5]
plt.figure(figsize=(30,10))
plt.pie(m.values[:10],labels=m.index[:10] ,colors = colors, autopct='%.0f%%')
plt.show
# m.index , m.value

"""From the above graph, cruelty by husband or relatives(domestic violence) is the most reported crime"""

m=df.groupby(['YEAR'])[['TOTAL CRIMES AGAINST WOMEN']].max().sort_values(['TOTAL CRIMES AGAINST WOMEN'],ascending=False)['TOTAL CRIMES AGAINST WOMEN']
colors = sns.color_palette('pastel')[0:10]
plt.figure(figsize=(30,10))
plt.pie(m.values[:10],labels=m.index[:10] ,colors = colors, autopct='%.0f%%')
plt.show
# m.index , m.value

df.groupby("YEAR")[['RAPE','SEXUAL HARRASSMENT','CRUETLY BY HUSBAND OR HIS RELATIVES']].max().plot(kind='bar',figsize=(22,7))

import matplotlib.pyplot as plt
states = ['Maharashtra', 'West Bengal', 'Telangana', 'Andhra Pradesh','Tamil Nadu']
for s in states:
    dh = df.loc[df.STATES == s]
    dh.plot(x='YEAR', y=list(dh.loc[:, dh.columns != 'YEAR']), figsize=(11,7))
    plt.figtext(1,0,s,backgroundcolor='green', color='white', size='large')
    plt.legend(loc='upper right', borderpad = 2)
    #print("test")

for s in states:
    c = sum(df.loc[df.STATES == s]['CRUETLY BY HUSBAND OR HIS RELATIVES'])
    d = sum(df.loc[df.STATES == s]['DOWRY DEATHS'])
    t = sum(df.loc[df.STATES == s]['TOTAL CRIMES AGAINST WOMEN'])
    #print('Percentage :- ', t - (c+d))
    plt.pie([t-(c+d), c, d], labels = ['Other crimes', 'Cruelty by husbands', 'Dowry deaths'] ,
           shadow = True, explode=[0.2, 0, 0], startangle=90)
    plt.title(s)
    plt.show()
    print('CRUETLY BY HUSBAND OR HIS RELATIVES: ', c)
    print('DOWRY DEATHS: ', d)
    print('TOTAL CRIMES AGAINST WOMEN', t)
    print('~'*100)

"""The above code calculates and visualizes the distribution of three types of crimes against women, namely other crimes, cruelty by husbands, and dowry deaths, across different states in India. The pie chart for each state displays the percentage of each type of crime. The results reveal that cruelty by husbands and dowry deaths are significant issues in many states, with some states reporting a high percentage of these types of crimes. The code provides a useful tool to identify the distribution of crimes against women across different states in India."""

df.set_index('STATES', inplace=True)

max_crimes = df['TOTAL CRIMES AGAINST WOMEN'].nlargest(10).plot(kind='barh', title='Most Unsafe States for Women', figsize=(6,5))
plt.xlabel('No. of Crimes')
plt.ylabel('STATES')
plt.show()

min_crimes = df['TOTAL CRIMES AGAINST WOMEN'].nsmallest(10).plot(kind='barh', title='Safest States for Women', figsize=(6,5))
plt.xlabel('No. of Crimes')
plt.ylabel('STATES')
plt.show()

import plotly.express as px
df.sort_values('RAPE', inplace=True);
fig = px.bar(x=df['STATES'][20:], y=df["RAPE"][20:], color=df["RAPE"][20:],
             labels={'x': "States", 'y': "Count"}, title="Rape Cases",
             color_continuous_scale='burg')
fig.show();

"""The bar chart shows the top 20 states in India with the highest number of reported rape cases. Madhya Pradesh has the highest number of reported rape cases, followed by Rajasthan, Uttar Pradesh, and Maharashtra. It's concerning to see such high numbers of reported cases, and this highlights the need for continued efforts to prevent and address violence against women in India."""

df.loc[df['HUMAN TRAFFICKING'] <= 15, 'STATES'] = 'Others' # Represent only large countries
fig = px.pie(df, values='HUMAN TRAFFICKING', names='STATES', title="Human Trafficking of Girls",
            color_discrete_sequence=px.colors.sequential.Teal_r, hole = 0.4)
fig.update_traces(textposition='inside', textinfo='label+value',
                 marker=dict(line=dict(color='#000000', width=2)))
fig.update_layout(annotations=[dict(text='count', x=0.5, y=0.5, font_size=20, showarrow=False)])
fig.show()

import seaborn as sns

df_numeric = df[(df['STATES'] != 'Others') & (df['STATES'] != 'Lakshadweep') & (df['STATES'] != 'Goa')]
sns.heatmap(df_numeric.drop(['YEAR', 'STATES'], axis=1).corr(), annot=True, cmap="YlGnBu")
labels=["RAPE","ASSAULT ON MODESTY","HUMAN TRAFFICKING","DOWRY DEATHS","KIDNAP & ABDUCTION","SEXUAL HARRASSMENT","IMORTAL TRAFFICKING"]
ticks=[0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]
plt.title("Heat Map for checking relationship b/w variables", pad=20, loc="left")
plt.xticks(ticks, labels)
plt.yticks(ticks, labels)
plt.show()

"""From the analysis, we can see that the crime rate is high in states like Madhya Pradesh, Uttar Pradesh, and Maharashtra, with the most common crime being rape. We also observe a strong positive correlation between various types of crimes. This information can help policymakers in formulating policies and measures to combat crime in these states."""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from plotly.offline import download_plotlyjs, init_notebook_mode , plot,iplot
import plotly.express as px
import plotly.graph_objects as go


from plotly.colors import n_colors
from plotly.subplots import make_subplots
init_notebook_mode(connected=True)
import cufflinks as cf
cf.go_offline()

g= pd.DataFrame(df.groupby(['YEAR'])['RAPE'].sum().reset_index())

g.columns=['Year','Cases Reported']
g

g1= pd.DataFrame(df.groupby(['STATES'])['RAPE'].sum().reset_index())
g1

g1.columns=['State/UT','Cases Reported']
g1.replace(to_replace='Arunachal Pradesh',value='Arunanchal Pradesh',inplace=True)
g1

"""#**Conclusion**
In conclusion, the "Crime against Women Analysis Project" is an important research initiative that seeks to address a critical issue affecting women worldwide. The project's comprehensive analysis of crime trends and contributing factors will provide valuable insights into the prevalence and nature of violence and harassment against women, which can inform policy development and intervention strategies. By raising awareness and generating data-driven recommendations, the project has the potential to bring about positive changes in the way society addresses and prevents crime against women. It is crucial to continue investing in research and initiatives like this to promote gender equality, human rights, and safer communities for all.
"""